# Lesson10

## reshape and squeeze

In [1]:
import torch

In [19]:
t = torch.tensor([[
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]]
],dtype=torch.float32)

In [20]:
t.size()

torch.Size([1, 3, 4])

In [21]:
t.shape

torch.Size([1, 3, 4])

In [22]:
len(t.shape)

3

In [23]:
torch.tensor(t.shape).prod()

tensor(12)

In [24]:
t.numel()

12

In [25]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [26]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [27]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [28]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [12]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [29]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [30]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [15]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [32]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [18]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [36]:
def flatten(t):
    t = t.reshape(1,-1)
    t=t.squeeze()
    return t

In [37]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

## cat

In [40]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [38]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [41]:
torch.cat((t1,t2),dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [42]:
torch.cat((t1,t2),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

# Lesson11

## flatten

In [44]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

In [45]:
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

In [47]:
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [48]:
t4 = torch.tensor([
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4]
])

In [50]:
t =torch.stack((t1,t2,t3)) 
t.shape

torch.Size([3, 4, 4])

In [51]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [52]:
t = t.reshape(3,1,4,4)

In [53]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [54]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [55]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [56]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [57]:
t[0][0][0][0]

tensor(1)

In [60]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [61]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [62]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [63]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [64]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [65]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Lesson12

## broadcast

In [66]:
import numpy as np

In [68]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype=torch.float32)
t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype=torch.float32)

Same shape is required!

In [69]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [70]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [71]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [72]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [73]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [74]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [75]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [76]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [77]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [78]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [79]:
t1 + 2 

tensor([[3., 4.],
        [5., 6.]])

In [80]:
t1 + torch.tensor(
np.broadcast_to(2,t1.shape)
,dtype=torch.float32
)

..\torch\csrc\utils\tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


tensor([[3., 4.],
        [5., 6.]])

In [83]:
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype=torch.float32)

t2=torch.tensor([2,4],dtype=torch.float32)

In [84]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

In [85]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
],dtype=torch.float32)

In [86]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [87]:
t.ge(0)
#大于等于

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [88]:
t.gt(0)
#大于

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [89]:
t.lt(0)
#小于

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [91]:
t.le(7)
#小于等于

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [92]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [93]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [94]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [95]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Lesson13

In [96]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

In [97]:
t.sum()

tensor(8.)

In [98]:
t.numel()
#计数

9

In [99]:
t.sum().numel()

1

In [100]:
#累乘
t.prod()

tensor(0.)

In [101]:
t.mean()

tensor(0.8889)

In [103]:
t.std()
#标准差

tensor(1.1667)

In [104]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [105]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [106]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

## argmax

In [110]:
t = torch.tensor([
    [1,0,0,1],
    [0,3,3,0],
    [4,0,0,5]
],dtype=torch.float32)

In [111]:
t.max()

tensor(5.)

In [112]:
t.argmax()

tensor(11)

In [113]:
t.flatten()

tensor([1., 0., 0., 1., 0., 3., 3., 0., 4., 0., 0., 5.])

In [114]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [115]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [116]:
t.max(dim=1)

torch.return_types.max(
values=tensor([1., 3., 5.]),
indices=tensor([3, 2, 3]))

In [117]:
t.argmax(dim=1)

tensor([3, 2, 3])

In [118]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype=torch.float32)

In [119]:
t.mean()

tensor(5.)

In [120]:
t.mean().item()
#获取元素值

5.0

In [121]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [122]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

# Lesson14

MNIST数据集
Fashion-MNIST